/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "complex_RPC.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static complex *
_scsuma_1 (scsuma_1_argument *argp, struct svc_req *rqstp)
{
	return (scsuma_1_svc(argp->a, argp->b, rqstp));
}

static complex *
_scproductoconescalar_1 (scproductoconescalar_1_argument *argp, struct svc_req *rqstp)
{
	return (scproductoconescalar_1_svc(argp->a, argp->c, rqstp));
}

static void
complex_operaciones_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		scsuma_1_argument scsuma_1_arg;
		scproductoconescalar_1_argument scproductoconescalar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case scSuma:
		_xdr_argument = (xdrproc_t) xdr_scsuma_1_argument;
		_xdr_result = (xdrproc_t) xdr_complex;
		local = (char *(*)(char *, struct svc_req *)) _scsuma_1;
		break;

	case scProductoConEscalar:
		_xdr_argument = (xdrproc_t) xdr_scproductoconescalar_1_argument;
		_xdr_result = (xdrproc_t) xdr_complex;
		local = (char *(*)(char *, struct svc_req *)) _scproductoconescalar_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (COMPLEX_OPERACIONES, COMPLEX_OPER_1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, COMPLEX_OPERACIONES, COMPLEX_OPER_1, complex_operaciones_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (COMPLEX_OPERACIONES, COMPLEX_OPER_1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, COMPLEX_OPERACIONES, COMPLEX_OPER_1, complex_operaciones_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (COMPLEX_OPERACIONES, COMPLEX_OPER_1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
