/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "complex_RPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

complex *
scsuma_1(complex a, complex b,  CLIENT *clnt)
{
	scsuma_1_argument arg;
	static complex clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.a = a;
	arg.b = b;
	if (clnt_call (clnt, scSuma, (xdrproc_t) xdr_scsuma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_complex, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

complex *
scproductoconescalar_1(complex a, double c,  CLIENT *clnt)
{
	scproductoconescalar_1_argument arg;
	static complex clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.a = a;
	arg.c = c;
	if (clnt_call (clnt, scProductoConEscalar, (xdrproc_t) xdr_scproductoconescalar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_complex, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
