/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "complex_RPC.h"

complex *
scsuma_1_svc(complex a, complex b,  struct svc_req *rqstp)
{
	static complex  result;

	complex scR;
   scR.fReal = a.fReal + b.fReal;
   scR.fImg = a.fImg + b.fImg;
	result=scR;
	return &result;
}

complex *
scproductoconescalar_1_svc(complex a, double c,  struct svc_req *rqstp)
{
	static complex  result;
	complex scR;
   scR.fReal = a.fReal * c;
   scR.fImg = a.fImg * c;
   result=scR; 

	return &result;
}
