/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remoteCalls_RPC.h"

bool_t
xdr_str (XDR *xdrs, str *objp)
{
	register int32_t *buf;

	 if (!xdr_STR (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_STR (XDR *xdrs, STR *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ln))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_DATA (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DATA (XDR *xdrs, DATA *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (2 +  1000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->arr, 1000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ln))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->key))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->arr;
					i < 1000; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->ln);
			IXDR_PUT_LONG(buf, objp->key);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (2 +  1000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->arr, 1000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ln))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->key))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->arr;
					i < 1000; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->ln = IXDR_GET_LONG(buf);
			objp->key = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->arr, 1000,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ln))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_issubstring_1_argument (XDR *xdrs, issubstring_1_argument *objp)
{
	 if (!xdr_str (xdrs, &objp->s1))
		 return FALSE;
	 if (!xdr_str (xdrs, &objp->s2))
		 return FALSE;
	return TRUE;
}
