

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remoteCalls_RPC.h"
#include <string.h>

void printArray_p(int arr[], int n) 
{ 
  int i; 
  for (i = 0; i < n; i++) 
      printf("%d ", arr[i]); 
  printf("\n"); 
} 

void
remotecalls_1(char *host,int op)
{

	CLIENT *clnt;
	int* res,n;
	long* res3;
	char st[1000];
	str s1,s2;
	data myData,*res2;
	int array[]={1,4,3,6,4,45,3,75,-12,23,0};
	myData.key=6;
	myData.ln=sizeof(array)/sizeof(array[0]);
	for(int i=0;i<myData.ln;i++){
		myData.arr[i]=array[i];
	}


#ifndef	DEBUG
	clnt = clnt_create (host, REMOTECALLS, REMOTECALLS_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	switch (op)
	{
	case 1:
		
		printf("Substring\ninput string 1: ");
		scanf("%s",st);
		s1.ln=strlen(st);
		for(int i=0;i<s1.ln;i++){s1.arr[i]=st[i];}

		printf("input string 2: ");
		scanf("%s",st);
		s2.ln=strlen(st);
		for(int i=0;i<s2.ln;i++){s2.arr[i]=st[i];}
		res=issubstring_1(s1, s2, clnt);
		printf("\n%s in %s\n",s2.arr,s1.arr);
		if (res == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if (*res <0) printf ("No es una subcadena\n");
		else printf("Es una subcadena\n");
		break;
	
	case 2:
		printArray_p(myData.arr,myData.ln);
		res=search_1(myData, clnt);
		if (res == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else printf("clave %d encontrada\n",myData.key);
		break;

	case 3:
		printArray_p(myData.arr,myData.ln);
		res2=sort_1(myData, clnt);
		if (res2 == (data *) NULL) {
			clnt_perror (clnt, "call failed");
		}else myData=*res2;
		printArray_p(myData.arr,myData.ln);
		break;
	case 4:
		printf("input n: ");
		scanf("%d",&n);
		res3=fact_1(n, clnt);
		if (res3 == (long *) NULL) {
			clnt_perror (clnt, "call failed");
		}else printf("%d! = %ld\n",n,*res3);
		break;
	default:
		break;
	}
	/*

	result_2 = search_1(search_1_myData, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = sort_1(sort_1_myData, clnt);
	if (result_3 == (data *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = printarray_1(printarray_1_myData, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = fact_1(fact_1_n, clnt);
	if (result_5 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int op=0;
	if (argc < 3) {
		printf ("usage: %s server_host, option\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	op=atoi(argv[2]);
	remotecalls_1 (host,op);
exit (0);
}
