/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "searchSort_RPC.h"

void printArray_p(int arr[], int n) 
{ 
  int i; 
  for (i = 0; i < n; i++) 
      printf("%d ", arr[i]); 
  printf("\n"); 
} 

void
substring_1(char *host)
{
	CLIENT *clnt;
	data    myData;
	int    *result_1;
	data   *result_2;
	void   *result_3;

	int array[]={1,4,3,6,4,45,3,75,-12,23,0};
	myData.key=6;
	myData.ln=sizeof(array)/sizeof(array[0]);
	for(int i=0;i<myData.ln;i++){
		myData.arr[i]=array[i];
	}

#ifndef	DEBUG
	clnt = clnt_create (host, SUBSTRING, SUBSTRING_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	printArray_p(myData.arr,myData.ln);

	result_2 = sort_1(myData, clnt);
	if (result_2 == (data *) NULL) {
		clnt_perror (clnt, "call failed");
	}else myData=*result_2;

	printArray_p(myData.arr,myData.ln);
	
	result_1 = search_1(myData, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else printf("clave %d encontrada en posicion; %d\n",myData.key,*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	substring_1 (host);
exit (0);
}
