/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "searchSort_RPC.h"

void printArray_p(int arr[], int n) 
{ 
  int i; 
  for (i = 0; i < n; i++) 
      printf("%d ", arr[i]); 
  printf("\n"); 
} 
void insertionSort(int* arr, int n) 
{ 
  int i, key, j; 
    for (i = 1; i < n; i++) { 
        key = arr[i]; 
        j = i - 1; 
  
      while (j >= 0 && arr[j] > key) { 
          arr[j + 1] = arr[j]; 
          j = j - 1; 
      } 
      arr[j + 1] = key; 
  } 
} 

int binarySearch(int arr[], int l, int r, int x) 
{ 
  if (r >= l) { 
    int mid = l + (r - l) / 2; 
    if (arr[mid] == x) 
        return mid; 
    if (arr[mid] > x) 
      return binarySearch(arr, l, mid - 1, x); 
    return binarySearch(arr, mid + 1, r, x); 
  } 
 
  return -1; 
} 

int *
search_1_svc(data myData,  struct svc_req *rqstp)
{
	static int  result;

	result=binarySearch(myData.arr,0,myData.ln,myData.key);

	return &result;
}

data *
sort_1_svc(data myData,  struct svc_req *rqstp)
{
	static data  tmp;

		tmp.key=myData.key;
    tmp.ln=myData.ln;
    for(int i=0;i<myData.ln;i++){ tmp.arr[i]=myData.arr[i];}
    insertionSort(tmp.arr,myData.ln);
    printArray_p(tmp.arr,tmp.ln);

	return &tmp;
}

void *
printarray_1_svc(data myData,  struct svc_req *rqstp)
{
	static char * result;

	printArray_p(myData.arr,myData.ln);

	return (void *) &result;
}
