/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SEARCHSORT_RPC_H_RPCGEN
#define _SEARCHSORT_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct STR data;

struct STR {
	int arr[1000];
	int ln;
	int key;
};
typedef struct STR STR;

#define SUBSTRING 0x20000001
#define SUBSTRING_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define search 1
extern  int * search_1(data , CLIENT *);
extern  int * search_1_svc(data , struct svc_req *);
#define sort 2
extern  data * sort_1(data , CLIENT *);
extern  data * sort_1_svc(data , struct svc_req *);
#define printArray 3
extern  void * printarray_1(data , CLIENT *);
extern  void * printarray_1_svc(data , struct svc_req *);
extern int substring_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define search 1
extern  int * search_1();
extern  int * search_1_svc();
#define sort 2
extern  data * sort_1();
extern  data * sort_1_svc();
#define printArray 3
extern  void * printarray_1();
extern  void * printarray_1_svc();
extern int substring_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_STR (XDR *, STR*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_STR ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SEARCHSORT_RPC_H_RPCGEN */
