/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FACTORIAL_RPC_H_RPCGEN
#define _FACTORIAL_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FACTORIAL 0x20000004
#define FACTORIAL_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define fact 1
extern  long * fact_1(int , CLIENT *);
extern  long * fact_1_svc(int , struct svc_req *);
extern int factorial_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fact 1
extern  long * fact_1();
extern  long * fact_1_svc();
extern int factorial_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FACTORIAL_RPC_H_RPCGEN */
