/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial_RPC.h"

long *
fact_1_svc(int n,  struct svc_req *rqstp)
{
	static long  result;

	if(n<=1) result= 1;
	else result=(long)n*(*fact_1_svc(n-1,rqstp));


	return &result;
}
