/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUBSTRING_RPC_H_RPCGEN
#define _SUBSTRING_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct STR str;

struct STR {
	char arr[100];
	int ln;
};
typedef struct STR STR;

struct issubstring_1_argument {
	str s1;
	str s2;
};
typedef struct issubstring_1_argument issubstring_1_argument;

#define SUBSTRING 0x20000001
#define SUBSTRING_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define isSubstring 1
extern  int * issubstring_1(str , str , CLIENT *);
extern  int * issubstring_1_svc(str , str , struct svc_req *);
extern int substring_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define isSubstring 1
extern  int * issubstring_1();
extern  int * issubstring_1_svc();
extern int substring_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str (XDR *, str*);
extern  bool_t xdr_STR (XDR *, STR*);
extern  bool_t xdr_issubstring_1_argument (XDR *, issubstring_1_argument*);

#else /* K&R C */
extern bool_t xdr_str ();
extern bool_t xdr_STR ();
extern bool_t xdr_issubstring_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUBSTRING_RPC_H_RPCGEN */
