/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "subString_RPC.h"
int runs=0;
int *
issubstring_1_svc(str s1, str s2,  struct svc_req *rqstp)
{
	static int  result;

	int M = s1.ln; 
  int N = s2.ln; 
  
    /* A loop to slide pat[] one by one */
  for (int i = 0; i <= N - M; i++) { 
    int j; 
		printf("Runs=%d ...\n",++runs);
    /* For current index i, check for pattern match */
    for (j = 0; j < M; j++) 
      if (s2.arr[i + j] != s1.arr[j]) 
          break; 
  
      if (j == M) 
				result=i;
        return &result; 
    } 


	result=-1;
	return &result;
}
