/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "subString_RPC.h"

bool_t
xdr_str (XDR *xdrs, str *objp)
{
	register int32_t *buf;

	 if (!xdr_STR (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_STR (XDR *xdrs, STR *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ln))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_issubstring_1_argument (XDR *xdrs, issubstring_1_argument *objp)
{
	 if (!xdr_str (xdrs, &objp->s1))
		 return FALSE;
	 if (!xdr_str (xdrs, &objp->s2))
		 return FALSE;
	return TRUE;
}
